import type { TMember } from "../types/members";

export const MEMBERS: readonly TMember[] = [
  {
    id: "nayeon",
    name: "Nayeon",
    fullName: "Im Nayeon",
    emoji: "🐰",
    social: [
      {
        platform: "instagram",
        username: "nayeonyny",
        url: "https://www.instagram.com/nayeonyny/",
      },
    ],
    color: "sky blue",
    nationality: "South Korean",
    birthday: new Date("1995-09-22"),
    positions: ["Main Vocalist", "Center", "Group Face"],
    songs: [
      {
        title: "POP!",
        links: [
          {
            platform: "youtube",
            url: "https://youtu.be/f6YDKF0LVWw?si=lVo3cXGAHFhGdDMF",
          },
          {
            platform: "spotify",
            url: "https://open.spotify.com/track/3lOMJTQTd6J34faYwASc33?si=7d2fc6f03dee4e03",
          },
          {
            platform: "appleMusic",
            url: "https://music.apple.com/us/song/pop/1624932774",
          },
        ],
      },
    ],
    funFacts: [
      "Her height is 163cm",
      "Her weight is 47kg",
      "She has a younger sister, Seoyeon, born 1998.",
      "She chose 9 as her favorite number, because TWICE has 9 members",
      "Her left leg is weak due to her being in a car accident in her childhood.",
    ],
  },
  {
    id: "jeongyeon",
    name: "Jeongyeon",
    fullName: "Yoo Jeong-yeon",
    emoji: "🐶",
    social: [
      {
        platform: "instagram",
        username: "jy_piece",
        url: "https://www.instagram.com/jy_piece/",
      },
    ],
    color: "green",
    nationality: "South Korean",
    birthday: new Date("1996-11-01"),
    positions: ["Main Vocalist"],
    songs: [],
    funFacts: [
      "Her height is 167cm",
      "Her weight is 50kg",
      "She has 2 older sisters: Gong Seungyeon (actress) and Seoyeon (office worker)",
      "She chose 0 as her favorite number, because she doesn't actually have a favorite number",
      "Her father, Yoo Changjoon, is a popular Korean traditional chef",
    ],
  },
  {
    id: "momo",
    name: "Momo",
    fullName: "Hirai Momo",
    emoji: "🍑",
    social: [
      {
        platform: "instagram",
        username: "momo",
        url: "https://www.instagram.com/momo/",
      },
    ],
    color: "pink",
    nationality: "Japanese",
    birthday: new Date("1996-11-09"),
    positions: ["Main Dancer", "Sub-Vocalist", "Sub-Rapper"],
    songs: [],
    funFacts: [
      "Her height is 167cm",
      "Her weight is 48kg",
      "She has an older sister, Hana, born in 1994.",
      "She chose 64 as her favorite number, because it's the number on her father's shirt when he plays football",
      "She was scouted by JYP Entertainment after they saw a dance video of her and her older sister.",
    ],
  },
  {
    id: "sana",
    name: "Sana",
    fullName: "Minatozaki Sana",
    emoji: "🐭",
    social: [
      {
        platform: "instagram",
        username: "m.by__sana",
        url: "https://www.instagram.com/m.by__sana/",
      },
    ],
    color: "purple",
    nationality: "Japanese",
    birthday: new Date("1996-12-29"),
    positions: ["Sub-Vocalist"],
    songs: [],
    funFacts: [
      "Her height is 168cm",
      "Her weight is 47kg",
      "She is an only child.",
      "She chose 12 as her favorite number (her birthday month), because Mina took the number 37.",
      "She likes spicy foods.",
    ],
  },
  {
    id: "jihyo",
    name: "Jihyo",
    fullName: "Park Ji-hyo",
    emoji: "🦄",
    social: [
      {
        platform: "instagram",
        username: "_zyozyo",
        url: "https://www.instagram.com/_zyozyo/",
      },
    ],
    color: "apricot",
    nationality: "South Korean",
    birthday: new Date("1997-02-01"),
    positions: ["Leader", "Main Vocalist"],
    songs: [],
    funFacts: [
      "Her height is 162cm",
      "Her weight is 56kg",
      "She has 2 younger sisters, Seoyeon (born in 2008)  and Jiyoung (born in 2002)",
      "She chose 21 as her favorite number, because she was born on February 1st.",
      "She was voted leader by the members, not JYPE (by anonymous voting).",
    ],
  },
  {
    id: "mina",
    name: "Mina",
    fullName: "Myoui Mina",
    emoji: "🐧",
    social: [
      {
        platform: "instagram",
        username: "mina_sr_my",
        url: "https://www.instagram.com/mina_sr_my/",
      },
    ],
    color: "mint",
    nationality: "Japanese",
    birthday: new Date("1997-03-24"),
    positions: ["Main Dancer", "Sub-Vocalist"],
    songs: [],
    funFacts: [
      "Her height is 163cm",
      "Her weight is 46kg",
      "She has an older brother, Kai, born in 1992.",
      "She was born in San Antonio, Texas, USA.",
      "She chose 37 as her favorite number, because “37” in Japanese it's pronounced as “Mi” or “San” (3) and “Nana” [often shortened to Na] (7)",
    ],
  },
  {
    id: "dahyun",
    name: "Dahyun",
    fullName: "Kim Da-hyun",
    emoji: "💛",
    social: [
      {
        platform: "instagram",
        username: "dahhyunnee",
        url: "https://www.instagram.com/dahhyunnee/",
      },
    ],
    color: "white",
    nationality: "South Korean",
    birthday: new Date("1997-05-28"),
    positions: ["Sub-Vocalist", "Main-Rapper"],
    songs: [],
    funFacts: [
      "Her height is 165cm",
      "Her weight is 48kg",
      "She has an older brother, Myungsoo.",
      "She chose 7 as her favorite number, because she became a TWICE member on July 7 and because she's the 7th oldest in TWICE.",
      "She is scared of animals (cats, dogs, etc.).",
    ],
  },
  {
    id: "chaeyoung",
    name: "Chaeyoung",
    fullName: "Son Chae-young",
    emoji: "🍓",
    social: [
      {
        platform: "instagram",
        username: "chaeyo.0",
        url: "https://www.instagram.com/chaeyo.0/",
      },
    ],
    color: "red",
    nationality: "South Korean",
    birthday: new Date("1997-04-23"),
    positions: ["Sub-Vocalist", "Main-Rapper"],
    songs: [],
    funFacts: [
      "Her height is 163cm",
      "Her weight is 46kg",
      "She has a younger brother, Jeonghun, born in 2000, who is an aspiring model.",
      "She chose 29 as her favorite number, because 2 (TWICE) and 9 (number of members)",
      "On April 5, 2024, it was rumored that she’s dating Korean rapper Zion.T before both of their companies confirmed the rumor on the same day.",
    ],
  },
  {
    id: "tzuyu",
    name: "Tzuyu",
    fullName: "Chou Tzuyu",
    emoji: "🦌",
    social: [
      {
        platform: "instagram",
        username: "thinkaboutzu",
        url: "https://www.instagram.com/thinkaboutzu/",
      },
    ],
    color: "blue",
    nationality: "Taiwanese",
    birthday: new Date("1999-06-14"),
    positions: ["Sub-Vocalist", "Visual", "Maknae"],
    songs: [],
    funFacts: [
      "Her height is 170cm",
      "Her weight is 48kg",
      "She has an older brother, born in 1992.",
      "Her favorite number is 25, because she thinks it is a cool number.",
      "She is the tallest member in the group.",
    ],
  },
] as const;
